### ISSUE TITLE
[機能][改善] 非整数vposでの描画の対応

### ISSUE THREAD

**Issue by rinsuki** [xpadev-net/niconicomments#97]
# 概要

- なにが：drawCanvas に渡すvposが
- どうなっていて：整数でないとうまく描画されない
- どうなってほしい：整数でなくても描画されるようになっていてほしい

とりあえず this.timeline の参照だけ Math.floor したものを使って、それ以外は非整数な vpos を使ったパッチを用意しました (これで何も出ないということはなくなる) https://github.com/rinsuki/niconicomments/commit/97709919071067fa683e103d89f3731c67c4fb24

一見ちゃんと動いている**ように見えます**が、適当に一本の動画で試しているだけなので、プラグインとかCA依存で壊れるかもしれません (内部構造に詳しくないのでこれでいいかわからない)

**Comment by xpadev-net** [comment]
こちらもありがとうございます！

非整数に対応するという意味であれば `drawCanvas` で受け取った `vpos` をすべてMath.floorすれば良いのではと思うのですが、`vposFloat` を分離したのはコメントをなめらかに動かしたいなどの意図でしょうか?

もしそうであれば `main.ts` の `_drawCollision` だけ `vposInt` に差し替えてPR投げていただけるとありがたいです🙇‍♂️

**Comment by rinsuki** [comment]
> vposFloat を分離したのはコメントをなめらかに動かしたいなどの意図でしょうか?

そうです！ (issueの本文に書くのを忘れていました…… :bow:)

> main.ts の _drawCollision だけ vposInt に差し替えてPR投げていただけるとありがたいです🙇‍♂️

わかりました！
