### ISSUE TITLE
[不具合][全般] NiconiComments.internal の型定義がおかしい

### ISSUE THREAD

**Issue by rinsuki** [xpadev-net/niconicomments#99]
# 概要

- 何が：`NiconiComments.internal` の型定義が
- どうなっていて： よくわからない感じになっている
  - ![image](https://github.com/xpadev-net/niconicomments/assets/6533808/44bf4dee-dc4d-45ef-8e04-40aeda285203)
- どうなってほしい：実行時の NiconiComments.internal.* と一致してほしい

**Comment by xpadev-net** [comment]
報告ありがとうございます
確認したところ型定義をビルドする際に使用していた `dts-bundle-generator` によって変数名が変更されていることがわかったため、修正を行いました
今日中にリリース出す予定なので少々お待ちください 🙇‍♂️
